# Generated by Django 4.1.7 on 2023-03-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_twitchidtouser_alter_twitchusers_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitchusers',
            name='msg_count',
            field=models.IntegerField(default=0),
        ),
    ]
