# Generated by Django 4.1.7 on 2023-03-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_twitchusers_msg_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitchusers',
            name='first_watch',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='twitchusers',
            name='follow_date',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='twitchusers',
            name='last_msg_timestamp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='twitchusers',
            name='notified_follow',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='twitchusers',
            name='pixels',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='twitchusers',
            name='unfollow',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='twitchusers',
            name='unfollow_date',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='twitchusers',
            name='watch_last_check',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='twitchusers',
            name='watch_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
