# Generated by Django 4.1.7 on 2023-03-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0005_remove_twitchusers_id_twitchusers_twitch_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="twitchusers",
            name="username",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="twitchusers",
            name="twitch_id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
